module excitation_module

contains

  ! Calculate the partition function for the given coolant.
  SUBROUTINE CALCULATE_PARTITION_FUNCTION(PARTITION_FUNCTION,NLEV,ENERGIES,WEIGHTS,TEMPERATURE)

    USE HEALPIX_TYPES
    IMPLICIT NONE

    INTEGER(KIND=I4B), INTENT(IN) :: NLEV
    REAL(KIND=DP), INTENT(IN)     :: ENERGIES(1:NLEV),WEIGHTS(1:NLEV)
    REAL(KIND=DP), INTENT(IN)     :: TEMPERATURE
    REAL(KIND=DP), INTENT(OUT)    :: PARTITION_FUNCTION

    INTEGER(KIND=I4B) :: ILEVEL

    PARTITION_FUNCTION=0.0D0
    DO ILEVEL=1,NLEV
      PARTITION_FUNCTION=PARTITION_FUNCTION + WEIGHTS(ILEVEL)*EXP(-ENERGIES(ILEVEL)/KB/TEMPERATURE)
    ENDDO

    RETURN
  END SUBROUTINE CALCULATE_PARTITION_FUNCTION

  ! Calculate LTE level populations for the given coolant.
  SUBROUTINE CALCULATE_LTE_POPULATIONS(NLEV,LEVEL_POP,ENERGIES,WEIGHTS,PARTITION_FUNCTION,DENSITY,TEMPERATURE)

    USE HEALPIX_TYPES
    IMPLICIT NONE

    INTEGER(KIND=I4B), INTENT(IN) :: NLEV
    REAL(KIND=DP), INTENT(IN)     :: ENERGIES(1:NLEV),WEIGHTS(1:NLEV)
    REAL(KIND=DP), INTENT(IN)     :: PARTITION_FUNCTION
    REAL(KIND=DP), INTENT(IN)     :: DENSITY,TEMPERATURE
    REAL(KIND=DP), INTENT(OUT)    :: LEVEL_POP(1:NLEV)

    INTEGER(KIND=I4B) :: ILEVEL
    REAL(KIND=DP) :: TOTAL_POP

    TOTAL_POP=0.0D0
    DO ILEVEL=1,NLEV
      LEVEL_POP(ILEVEL)=DENSITY*WEIGHTS(ILEVEL)*EXP(-ENERGIES(ILEVEL)/KB/TEMPERATURE)/PARTITION_FUNCTION
      TOTAL_POP=TOTAL_POP + LEVEL_POP(ILEVEL)
    ENDDO

    ! Check that the sum of the level populations adds up to the total density.
    IF(ABS(TOTAL_POP-DENSITY)/DENSITY.GT.1.0D-3) THEN
      WRITE(6,*)'ERROR! Sum of LTE level populations differs from the total density by ', &
          & INT(1.0D2*ABS(TOTAL_POP-DENSITY)/DENSITY),'%'
      STOP
    ENDIF

    RETURN
  END SUBROUTINE CALCULATE_LTE_POPULATIONS

end module excitation_module
